"""Generate Android resources and the canonical-message lookup. No network required."""
import hashlib, json, pathlib
from xml.sax.saxutils import escape
ROOT=pathlib.Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'tools/localization.json').read_text())
def ident(s): return 'text_'+hashlib.sha256(s.encode()).hexdigest()[:16]
def java(s): return json.dumps(s,ensure_ascii=False)
def xml(s):
    return '"'+escape(s.replace('\\','\\\\').replace('"','\\"').replace("'","\\'").replace('\n','\\n'))+'"'
for lang,directory in [('id','values'),('en','values-en')]:
    target=ROOT/'app/src/main/res'/directory; target.mkdir(exist_ok=True)
    (target/'localized_strings.xml').write_text('<resources>\n'+''.join('    <string name="'+ident(k)+'" formatted="false">'+xml(v[lang])+'</string>\n' for k,v in data.items())+'</resources>\n')
out=ROOT/'app/src/main/java/com/tgdrive/mobile/TranslationCatalog.java'
out.write_text('''// Generated by tools/generate_localization.py. Edit tools/localization.json instead.
package com.tgdrive.mobile;
import java.util.LinkedHashMap;
final class TranslationCatalog {
    static final LinkedHashMap<String, Integer> IDS = new LinkedHashMap<>();
    static {
'''+''.join('        IDS.put('+java(k)+', R.string.'+ident(k)+');\n' for k in data)+'''    }
    private TranslationCatalog() { }
}
''')
print(f'Generated {len(data)} paired translations')
